// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat-group.proto

package chatgroup

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Member struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_faeb59228c972231, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Member) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type MemberList struct {
	// creates a slice of Member
	Member               []*Member `protobuf:"bytes,1,rep,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberList) Reset()         { *m = MemberList{} }
func (m *MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()    {}
func (*MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_faeb59228c972231, []int{1}
}
func (m *MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberList.Unmarshal(m, b)
}
func (m *MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberList.Marshal(b, m, deterministic)
}
func (dst *MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberList.Merge(dst, src)
}
func (m *MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberList.Size(m)
}
func (m *MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberList proto.InternalMessageInfo

func (m *MemberList) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type Message struct {
	Sender               *Member  `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_faeb59228c972231, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSender() *Member {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// Empty message type used for List method
type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_faeb59228c972231, []int{3}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Member)(nil), "chatgroup.Member")
	proto.RegisterType((*MemberList)(nil), "chatgroup.MemberList")
	proto.RegisterType((*Message)(nil), "chatgroup.Message")
	proto.RegisterType((*Void)(nil), "chatgroup.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublisherClient is the client API for Publisher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublisherClient interface {
	ListSubscriber(ctx context.Context, in *Void, opts ...grpc.CallOption) (*MemberList, error)
	Subscribe(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error)
	Unsubscribe(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error)
	Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MemberList, error)
}

type publisherClient struct {
	cc *grpc.ClientConn
}

func NewPublisherClient(cc *grpc.ClientConn) PublisherClient {
	return &publisherClient{cc}
}

func (c *publisherClient) ListSubscriber(ctx context.Context, in *Void, opts ...grpc.CallOption) (*MemberList, error) {
	out := new(MemberList)
	err := c.cc.Invoke(ctx, "/chatgroup.Publisher/ListSubscriber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) Subscribe(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/chatgroup.Publisher/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) Unsubscribe(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/chatgroup.Publisher/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MemberList, error) {
	out := new(MemberList)
	err := c.cc.Invoke(ctx, "/chatgroup.Publisher/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublisherServer is the server API for Publisher service.
type PublisherServer interface {
	ListSubscriber(context.Context, *Void) (*MemberList, error)
	Subscribe(context.Context, *Member) (*Member, error)
	Unsubscribe(context.Context, *Member) (*Member, error)
	Publish(context.Context, *Message) (*MemberList, error)
}

func RegisterPublisherServer(s *grpc.Server, srv PublisherServer) {
	s.RegisterService(&_Publisher_serviceDesc, srv)
}

func _Publisher_ListSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).ListSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgroup.Publisher/ListSubscriber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).ListSubscriber(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgroup.Publisher/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Subscribe(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgroup.Publisher/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Unsubscribe(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgroup.Publisher/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Publish(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Publisher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatgroup.Publisher",
	HandlerType: (*PublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSubscriber",
			Handler:    _Publisher_ListSubscriber_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _Publisher_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _Publisher_Unsubscribe_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Publisher_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat-group.proto",
}

// DisplayerClient is the client API for Displayer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DisplayerClient interface {
	DisplayText(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	DisplaySubscription(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error)
	DisplayUnsubscription(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error)
}

type displayerClient struct {
	cc *grpc.ClientConn
}

func NewDisplayerClient(cc *grpc.ClientConn) DisplayerClient {
	return &displayerClient{cc}
}

func (c *displayerClient) DisplayText(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chatgroup.Displayer/DisplayText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayerClient) DisplaySubscription(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/chatgroup.Displayer/DisplaySubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayerClient) DisplayUnsubscription(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/chatgroup.Displayer/DisplayUnsubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisplayerServer is the server API for Displayer service.
type DisplayerServer interface {
	DisplayText(context.Context, *Message) (*Message, error)
	DisplaySubscription(context.Context, *Member) (*Member, error)
	DisplayUnsubscription(context.Context, *Member) (*Member, error)
}

func RegisterDisplayerServer(s *grpc.Server, srv DisplayerServer) {
	s.RegisterService(&_Displayer_serviceDesc, srv)
}

func _Displayer_DisplayText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayerServer).DisplayText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgroup.Displayer/DisplayText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayerServer).DisplayText(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Displayer_DisplaySubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayerServer).DisplaySubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgroup.Displayer/DisplaySubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayerServer).DisplaySubscription(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

func _Displayer_DisplayUnsubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayerServer).DisplayUnsubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgroup.Displayer/DisplayUnsubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayerServer).DisplayUnsubscription(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

var _Displayer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatgroup.Displayer",
	HandlerType: (*DisplayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisplayText",
			Handler:    _Displayer_DisplayText_Handler,
		},
		{
			MethodName: "DisplaySubscription",
			Handler:    _Displayer_DisplaySubscription_Handler,
		},
		{
			MethodName: "DisplayUnsubscription",
			Handler:    _Displayer_DisplayUnsubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat-group.proto",
}

func init() { proto.RegisterFile("chat-group.proto", fileDescriptor_chat_group_faeb59228c972231) }

var fileDescriptor_chat_group_faeb59228c972231 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x6a, 0xf3, 0x30,
	0x14, 0xc5, 0xa3, 0x24, 0x38, 0xf8, 0x1a, 0xf2, 0x7d, 0xbd, 0x25, 0x60, 0x32, 0x05, 0x4d, 0xe9,
	0x50, 0x0f, 0x0e, 0x6d, 0xa0, 0x50, 0xda, 0xa1, 0x43, 0x87, 0x06, 0x4a, 0xfa, 0x67, 0xb7, 0x13,
	0x91, 0x08, 0x62, 0x4b, 0x48, 0x32, 0xa4, 0xef, 0xd7, 0xb7, 0xe9, 0x4b, 0x14, 0xc9, 0xc2, 0xb4,
	0x38, 0x81, 0x66, 0xbb, 0x3a, 0x3e, 0xbf, 0xa3, 0x73, 0x8d, 0xe0, 0xff, 0x6a, 0x9b, 0x99, 0xcb,
	0x8d, 0x12, 0x95, 0x4c, 0xa4, 0x12, 0x46, 0x60, 0x68, 0x15, 0x27, 0xd0, 0x7b, 0x08, 0x16, 0xac,
	0xc8, 0x99, 0x42, 0x84, 0x7e, 0x99, 0x15, 0x2c, 0x26, 0x13, 0x32, 0x0d, 0x97, 0x6e, 0xc6, 0x21,
	0x74, 0xb9, 0x8c, 0xbb, 0x4e, 0xe9, 0x72, 0x69, 0x3d, 0x52, 0x28, 0x13, 0xf7, 0x6a, 0x8f, 0x9d,
	0xe9, 0x1c, 0xa0, 0x4e, 0x78, 0xe2, 0xda, 0xe0, 0x05, 0x04, 0x85, 0x3b, 0xc5, 0x64, 0xd2, 0x9b,
	0x46, 0xe9, 0x59, 0xd2, 0xdc, 0x95, 0xd4, 0xb6, 0xa5, 0x37, 0xd0, 0x47, 0x18, 0x2c, 0x98, 0xd6,
	0xd9, 0x86, 0x59, 0x4a, 0xb3, 0x72, 0xed, 0x28, 0x72, 0x84, 0xaa, 0x0d, 0xb6, 0x82, 0x61, 0x7b,
	0xe3, 0x4b, 0xb9, 0x99, 0x06, 0xd0, 0x7f, 0x17, 0x7c, 0x9d, 0x7e, 0x11, 0x08, 0x9f, 0xab, 0x7c,
	0xc7, 0xf5, 0x96, 0x29, 0xbc, 0x81, 0xa1, 0xad, 0xf4, 0x52, 0xe5, 0x7a, 0xa5, 0xb8, 0x5d, 0xf1,
	0xdf, 0x8f, 0x58, 0x0b, 0x8c, 0x47, 0xad, 0x7b, 0x2c, 0x41, 0x3b, 0x38, 0x83, 0xb0, 0xe1, 0xb0,
	0xdd, 0x66, 0xdc, 0x96, 0x68, 0x07, 0xaf, 0x20, 0x7a, 0x2b, 0xf5, 0xc9, 0xd8, 0x35, 0x0c, 0x7c,
	0x69, 0xc4, 0x5f, 0xdf, 0xdd, 0xbf, 0x39, 0xda, 0x31, 0xfd, 0x24, 0x10, 0x3e, 0x70, 0x2d, 0x77,
	0xd9, 0x07, 0x53, 0x38, 0x87, 0xc8, 0x1f, 0x5e, 0xd9, 0xde, 0x1c, 0x4c, 0x3a, 0xa0, 0xd1, 0x0e,
	0xde, 0xc2, 0xb9, 0x07, 0xfd, 0xc6, 0xd2, 0x70, 0x51, 0xfe, 0xb9, 0xfd, 0x1d, 0x8c, 0x3c, 0xde,
	0xec, 0x7e, 0x52, 0x40, 0x1e, 0xb8, 0x37, 0x39, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x71, 0xb6,
	0xf0, 0xc6, 0xa7, 0x02, 0x00, 0x00,
}
