// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat-group.proto

package chatgroup

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_SUBSCRIBE_REQUEST   Message_MessageType = 0
	Message_SUBSCRIBE_REPLY     Message_MessageType = 1
	Message_UNSUBSCRIBE_REQUEST Message_MessageType = 2
	Message_UNSUBSCRIBE_REPLY   Message_MessageType = 3
	Message_PUBLISH_REQUEST     Message_MessageType = 4
	Message_PUBLISH_REPLY       Message_MessageType = 5
	Message_MEMBERLIST_REQUEST  Message_MessageType = 6
	Message_MEMBERLIST_REPLY    Message_MessageType = 7
	Message_CMD_LIST_REQUEST    Message_MessageType = 8
	Message_CMD_LIST_REPLY      Message_MessageType = 9
)

var Message_MessageType_name = map[int32]string{
	0: "SUBSCRIBE_REQUEST",
	1: "SUBSCRIBE_REPLY",
	2: "UNSUBSCRIBE_REQUEST",
	3: "UNSUBSCRIBE_REPLY",
	4: "PUBLISH_REQUEST",
	5: "PUBLISH_REPLY",
	6: "MEMBERLIST_REQUEST",
	7: "MEMBERLIST_REPLY",
	8: "CMD_LIST_REQUEST",
	9: "CMD_LIST_REPLY",
}
var Message_MessageType_value = map[string]int32{
	"SUBSCRIBE_REQUEST":   0,
	"SUBSCRIBE_REPLY":     1,
	"UNSUBSCRIBE_REQUEST": 2,
	"UNSUBSCRIBE_REPLY":   3,
	"PUBLISH_REQUEST":     4,
	"PUBLISH_REPLY":       5,
	"MEMBERLIST_REQUEST":  6,
	"MEMBERLIST_REPLY":    7,
	"CMD_LIST_REQUEST":    8,
	"CMD_LIST_REPLY":      9,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_992737e6009286fc, []int{2, 0}
}

type Member struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Leader               bool     `protobuf:"varint,4,opt,name=leader" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_992737e6009286fc, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Member) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Member) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

type MemberList struct {
	Member               []*Member `protobuf:"bytes,1,rep,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberList) Reset()         { *m = MemberList{} }
func (m *MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()    {}
func (*MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_992737e6009286fc, []int{1}
}
func (m *MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberList.Unmarshal(m, b)
}
func (m *MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberList.Marshal(b, m, deterministic)
}
func (dst *MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberList.Merge(dst, src)
}
func (m *MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberList.Size(m)
}
func (m *MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberList proto.InternalMessageInfo

func (m *MemberList) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type Message struct {
	MsgType              Message_MessageType `protobuf:"varint,1,opt,name=msgType,enum=chatgroup.Message_MessageType" json:"msgType,omitempty"`
	Sender               *Member             `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	Text                 string              `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	MemberList           *MemberList         `protobuf:"bytes,4,opt,name=memberList" json:"memberList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_992737e6009286fc, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() Message_MessageType {
	if m != nil {
		return m.MsgType
	}
	return Message_SUBSCRIBE_REQUEST
}

func (m *Message) GetSender() *Member {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetMemberList() *MemberList {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func init() {
	proto.RegisterType((*Member)(nil), "chatgroup.Member")
	proto.RegisterType((*MemberList)(nil), "chatgroup.MemberList")
	proto.RegisterType((*Message)(nil), "chatgroup.Message")
	proto.RegisterEnum("chatgroup.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("chat-group.proto", fileDescriptor_chat_group_992737e6009286fc) }

var fileDescriptor_chat_group_992737e6009286fc = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4e, 0xb3, 0x40,
	0x10, 0xc7, 0x3f, 0xa0, 0x1f, 0x6d, 0xa7, 0xb1, 0xd2, 0xa9, 0xad, 0x9c, 0x4c, 0xc3, 0xa9, 0x1e,
	0xec, 0xa1, 0xc6, 0xe8, 0x99, 0x4a, 0x62, 0x13, 0x30, 0x75, 0x29, 0x89, 0x9e, 0x1a, 0xaa, 0x9b,
	0x4a, 0x22, 0x65, 0x03, 0x98, 0xe8, 0x03, 0xf9, 0x70, 0xbe, 0x85, 0x99, 0xa5, 0x45, 0x48, 0x3d,
	0x31, 0xfb, 0xdb, 0x1f, 0x33, 0xff, 0x49, 0x16, 0x8c, 0xe7, 0xd7, 0x30, 0xbf, 0xd8, 0xa4, 0xc9,
	0xbb, 0x98, 0x88, 0x34, 0xc9, 0x13, 0x6c, 0x13, 0x91, 0xc0, 0x7a, 0x04, 0xdd, 0xe3, 0xf1, 0x9a,
	0xa7, 0x88, 0xd0, 0xd8, 0x86, 0x31, 0x37, 0x95, 0x91, 0x32, 0x6e, 0x33, 0x59, 0x63, 0x17, 0xd4,
	0x48, 0x98, 0xaa, 0x24, 0x6a, 0x24, 0xc8, 0x11, 0x49, 0x9a, 0x9b, 0x5a, 0xe1, 0x50, 0x8d, 0x43,
	0xd0, 0xdf, 0x78, 0xf8, 0xc2, 0x53, 0xb3, 0x31, 0x52, 0xc6, 0x2d, 0xb6, 0x3b, 0x59, 0xd7, 0x00,
	0x45, 0x67, 0x37, 0xca, 0x72, 0x3c, 0x07, 0x3d, 0x96, 0x27, 0x53, 0x19, 0x69, 0xe3, 0xce, 0xb4,
	0x37, 0x29, 0x33, 0x4c, 0x0a, 0x8d, 0xed, 0x04, 0xeb, 0x4b, 0x83, 0xa6, 0xc7, 0xb3, 0x2c, 0xdc,
	0x70, 0xbc, 0x81, 0x66, 0x9c, 0x6d, 0x96, 0x9f, 0xa2, 0xc8, 0xd5, 0x9d, 0x9e, 0xd5, 0xfe, 0x93,
	0xd2, 0xfe, 0x4b, 0x16, 0xdb, 0xeb, 0x34, 0x30, 0xe3, 0x5b, 0x8a, 0x45, 0xf1, 0xff, 0x1e, 0x58,
	0x08, 0xb4, 0x55, 0xce, 0x3f, 0xca, 0xad, 0xa8, 0xc6, 0x2b, 0x80, 0xb8, 0x4c, 0x2f, 0x37, 0xeb,
	0x4c, 0x07, 0x07, 0x2d, 0xe8, 0x92, 0x55, 0x44, 0xeb, 0x5b, 0x81, 0x4e, 0x25, 0x0e, 0x0e, 0xa0,
	0xe7, 0x07, 0xb6, 0x3f, 0x63, 0x73, 0xdb, 0x59, 0x31, 0xe7, 0x21, 0x70, 0xfc, 0xa5, 0xf1, 0x0f,
	0xfb, 0x70, 0x5c, 0xc5, 0x0b, 0xf7, 0xc9, 0x50, 0xf0, 0x14, 0xfa, 0xc1, 0xfd, 0xa1, 0xad, 0x52,
	0x93, 0xfa, 0x05, 0xf9, 0x1a, 0x35, 0x59, 0x04, 0xb6, 0x3b, 0xf7, 0xef, 0x4a, 0xb7, 0x81, 0x3d,
	0x38, 0xfa, 0x85, 0xe4, 0xfd, 0xc7, 0x21, 0xa0, 0xe7, 0x78, 0xb6, 0xc3, 0xdc, 0xb9, 0xbf, 0x2c,
	0x55, 0x1d, 0x4f, 0xc0, 0xa8, 0x71, 0xb2, 0x9b, 0x44, 0x67, 0xde, 0xed, 0xaa, 0xe6, 0xb6, 0x10,
	0xa1, 0x5b, 0xa1, 0x64, 0xb6, 0xd7, 0xba, 0x7c, 0x4c, 0x97, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x6a, 0x6d, 0xc7, 0xce, 0x60, 0x02, 0x00, 0x00,
}
