// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat-message.proto

package chatmessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Chatmessage struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chatmessage) Reset()         { *m = Chatmessage{} }
func (m *Chatmessage) String() string { return proto.CompactTextString(m) }
func (*Chatmessage) ProtoMessage()    {}
func (*Chatmessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_message_4272cfd0b1ecfaab, []int{0}
}
func (m *Chatmessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chatmessage.Unmarshal(m, b)
}
func (m *Chatmessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chatmessage.Marshal(b, m, deterministic)
}
func (dst *Chatmessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chatmessage.Merge(dst, src)
}
func (m *Chatmessage) XXX_Size() int {
	return xxx_messageInfo_Chatmessage.Size(m)
}
func (m *Chatmessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Chatmessage.DiscardUnknown(m)
}

var xxx_messageInfo_Chatmessage proto.InternalMessageInfo

func (m *Chatmessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Chatmessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func init() {
	proto.RegisterType((*Chatmessage)(nil), "chatmessage.chatmessage")
}

func init() { proto.RegisterFile("chat-message.proto", fileDescriptor_chat_message_4272cfd0b1ecfaab) }

var fileDescriptor_chat_message_4272cfd0b1ecfaab = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0xcd, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x06, 0x89, 0x41, 0x85, 0x94, 0x4c, 0xb9, 0x90, 0xb9, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0xa9, 0x15,
	0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0x2c, 0xad, 0x28, 0x3f, 0x57,
	0x82, 0x09, 0x22, 0x06, 0x62, 0x27, 0xb1, 0x81, 0x8d, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0x6f, 0x8a, 0x80, 0x60, 0x00, 0x00, 0x00,
}
