// Code generated by protoc-gen-go. DO NOT EDIT.
// source: memberlist.proto

package memberlist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Member struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Leader               bool     `protobuf:"varint,4,opt,name=leader" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_memberlist_f9d7a084e3c45593, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Member) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Member) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

type MemberList struct {
	// creates a slice of Member
	List                 []*Member `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberList) Reset()         { *m = MemberList{} }
func (m *MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()    {}
func (*MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_memberlist_f9d7a084e3c45593, []int{1}
}
func (m *MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberList.Unmarshal(m, b)
}
func (m *MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberList.Marshal(b, m, deterministic)
}
func (dst *MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberList.Merge(dst, src)
}
func (m *MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberList.Size(m)
}
func (m *MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberList proto.InternalMessageInfo

func (m *MemberList) GetList() []*Member {
	if m != nil {
		return m.List
	}
	return nil
}

// Empty message type used for Read method
type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_memberlist_f9d7a084e3c45593, []int{2}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Member)(nil), "memberlist.Member")
	proto.RegisterType((*MemberList)(nil), "memberlist.MemberList")
	proto.RegisterType((*Void)(nil), "memberlist.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MembersClient is the client API for Members service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MembersClient interface {
	List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*MemberList, error)
}

type membersClient struct {
	cc *grpc.ClientConn
}

func NewMembersClient(cc *grpc.ClientConn) MembersClient {
	return &membersClient{cc}
}

func (c *membersClient) List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*MemberList, error) {
	out := new(MemberList)
	err := c.cc.Invoke(ctx, "/memberlist.Members/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembersServer is the server API for Members service.
type MembersServer interface {
	List(context.Context, *Void) (*MemberList, error)
}

func RegisterMembersServer(s *grpc.Server, srv MembersServer) {
	s.RegisterService(&_Members_serviceDesc, srv)
}

func _Members_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memberlist.Members/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).List(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _Members_serviceDesc = grpc.ServiceDesc{
	ServiceName: "memberlist.Members",
	HandlerType: (*MembersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Members_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memberlist.proto",
}

func init() { proto.RegisterFile("memberlist.proto", fileDescriptor_memberlist_f9d7a084e3c45593) }

var fileDescriptor_memberlist_f9d7a084e3c45593 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0x4d, 0x1b, 0xa2, 0x9e, 0x20, 0xe5, 0x86, 0x12, 0x9c, 0x4a, 0x06, 0xe9, 0xd4, 0xa1,
	0xba, 0xfa, 0x0f, 0x74, 0xe9, 0x20, 0xae, 0x2d, 0xcd, 0x10, 0x68, 0x4d, 0x48, 0xf3, 0xff, 0x91,
	0x5c, 0x04, 0x0b, 0x6e, 0xef, 0xbd, 0x7c, 0x79, 0x77, 0x07, 0xc5, 0xac, 0xe7, 0x41, 0xfb, 0xc9,
	0x2c, 0xa1, 0x71, 0xde, 0x06, 0x8b, 0xf0, 0x4b, 0xd4, 0x0b, 0xc4, 0x83, 0x1c, 0x22, 0xf0, 0x77,
	0x3f, 0x6b, 0xc9, 0x2a, 0x56, 0xef, 0x3b, 0xd2, 0x78, 0x84, 0xcc, 0x38, 0x99, 0x51, 0x92, 0x19,
	0x17, 0x19, 0x67, 0x7d, 0x90, 0x79, 0x62, 0xa2, 0xc6, 0x12, 0xc4, 0xa4, 0xfb, 0x51, 0x7b, 0xc9,
	0x2b, 0x56, 0xef, 0xba, 0xaf, 0x53, 0x57, 0x80, 0xd4, 0x7c, 0x37, 0x4b, 0xc0, 0x33, 0xf0, 0x38,
	0x4f, 0xb2, 0x2a, 0xaf, 0x0f, 0x2d, 0x36, 0xab, 0xa5, 0x12, 0xd5, 0xd1, 0xbb, 0x12, 0xc0, 0x9f,
	0xd6, 0x8c, 0xed, 0x0d, 0xb6, 0x29, 0x5f, 0xb0, 0x05, 0x4e, 0x15, 0xc5, 0xfa, 0x53, 0x84, 0x4e,
	0xe5, 0x7f, 0x4d, 0x24, 0xd5, 0x66, 0x10, 0x74, 0xe9, 0xe5, 0x13, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0xb4, 0x2a, 0x22, 0xfd, 0x00, 0x00, 0x00,
}
