// Code generated by protoc-gen-go. DO NOT EDIT.
// source: display.proto

package display

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sender struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Leader               bool     `protobuf:"varint,4,opt,name=leader" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sender) Reset()         { *m = Sender{} }
func (m *Sender) String() string { return proto.CompactTextString(m) }
func (*Sender) ProtoMessage()    {}
func (*Sender) Descriptor() ([]byte, []int) {
	return fileDescriptor_display_2d856e9012ebaee1, []int{0}
}
func (m *Sender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sender.Unmarshal(m, b)
}
func (m *Sender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sender.Marshal(b, m, deterministic)
}
func (dst *Sender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sender.Merge(dst, src)
}
func (m *Sender) XXX_Size() int {
	return xxx_messageInfo_Sender.Size(m)
}
func (m *Sender) XXX_DiscardUnknown() {
	xxx_messageInfo_Sender.DiscardUnknown(m)
}

var xxx_messageInfo_Sender proto.InternalMessageInfo

func (m *Sender) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sender) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Sender) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Sender) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

type Tweet struct {
	Sender               *Sender  `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tweet) Reset()         { *m = Tweet{} }
func (m *Tweet) String() string { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()    {}
func (*Tweet) Descriptor() ([]byte, []int) {
	return fileDescriptor_display_2d856e9012ebaee1, []int{1}
}
func (m *Tweet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tweet.Unmarshal(m, b)
}
func (m *Tweet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tweet.Marshal(b, m, deterministic)
}
func (dst *Tweet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tweet.Merge(dst, src)
}
func (m *Tweet) XXX_Size() int {
	return xxx_messageInfo_Tweet.Size(m)
}
func (m *Tweet) XXX_DiscardUnknown() {
	xxx_messageInfo_Tweet.DiscardUnknown(m)
}

var xxx_messageInfo_Tweet proto.InternalMessageInfo

func (m *Tweet) GetSender() *Sender {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Tweet) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Sender)(nil), "display.Sender")
	proto.RegisterType((*Tweet)(nil), "display.Tweet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DisplayTweetsClient is the client API for DisplayTweets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DisplayTweetsClient interface {
	Display(ctx context.Context, in *Tweet, opts ...grpc.CallOption) (*Tweet, error)
}

type displayTweetsClient struct {
	cc *grpc.ClientConn
}

func NewDisplayTweetsClient(cc *grpc.ClientConn) DisplayTweetsClient {
	return &displayTweetsClient{cc}
}

func (c *displayTweetsClient) Display(ctx context.Context, in *Tweet, opts ...grpc.CallOption) (*Tweet, error) {
	out := new(Tweet)
	err := c.cc.Invoke(ctx, "/display.DisplayTweets/Display", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisplayTweetsServer is the server API for DisplayTweets service.
type DisplayTweetsServer interface {
	Display(context.Context, *Tweet) (*Tweet, error)
}

func RegisterDisplayTweetsServer(s *grpc.Server, srv DisplayTweetsServer) {
	s.RegisterService(&_DisplayTweets_serviceDesc, srv)
}

func _DisplayTweets_Display_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayTweetsServer).Display(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/display.DisplayTweets/Display",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayTweetsServer).Display(ctx, req.(*Tweet))
	}
	return interceptor(ctx, in, info, handler)
}

var _DisplayTweets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "display.DisplayTweets",
	HandlerType: (*DisplayTweetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Display",
			Handler:    _DisplayTweets_Display_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "display.proto",
}

func init() { proto.RegisterFile("display.proto", fileDescriptor_display_2d856e9012ebaee1) }

var fileDescriptor_display_2d856e9012ebaee1 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xc9, 0x2c, 0x2e,
	0xc8, 0x49, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x22, 0xb8,
	0xd8, 0x82, 0x53, 0xf3, 0x52, 0x52, 0x8b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x02, 0x09, 0x26,
	0xb0, 0x08, 0x53, 0x66, 0x01, 0x48, 0x4d, 0x41, 0x7e, 0x51, 0x89, 0x04, 0x33, 0x44, 0x0d, 0x88,
	0x2d, 0x24, 0xc6, 0xc5, 0x96, 0x93, 0x9a, 0x98, 0x92, 0x5a, 0x24, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1,
	0x11, 0x04, 0xe5, 0x29, 0xb9, 0x70, 0xb1, 0x86, 0x94, 0xa7, 0xa6, 0x96, 0x08, 0xa9, 0x73, 0xb1,
	0x15, 0x83, 0xad, 0x00, 0x1b, 0xcd, 0x6d, 0xc4, 0xaf, 0x07, 0x73, 0x0b, 0xc4, 0xe6, 0x20, 0xa8,
	0x34, 0xc8, 0xf4, 0x92, 0xd4, 0x8a, 0x12, 0xa8, 0x7d, 0x60, 0xb6, 0x91, 0x0d, 0x17, 0xaf, 0x0b,
	0x44, 0x35, 0xd8, 0xb0, 0x62, 0x21, 0x6d, 0x2e, 0x76, 0xa8, 0x80, 0x10, 0x1f, 0xdc, 0x20, 0xb0,
	0x9c, 0x14, 0x1a, 0x5f, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x5b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x25, 0x9f, 0x6a, 0xf6, 0xfe, 0x00, 0x00, 0x00,
}
