// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leaderlist.proto

package leaderlist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Leader_LeaderStatus int32

const (
	Leader_UNKNOWN   Leader_LeaderStatus = 0
	Leader_SERVICE   Leader_LeaderStatus = 1
	Leader_WORKING   Leader_LeaderStatus = 2
	Leader_CANDIDATE Leader_LeaderStatus = 3
	// Not to be assigned to leader
	Leader_NOTFOUND Leader_LeaderStatus = 4
)

var Leader_LeaderStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVICE",
	2: "WORKING",
	3: "CANDIDATE",
	4: "NOTFOUND",
}
var Leader_LeaderStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"SERVICE":   1,
	"WORKING":   2,
	"CANDIDATE": 3,
	"NOTFOUND":  4,
}

func (x Leader_LeaderStatus) String() string {
	return proto.EnumName(Leader_LeaderStatus_name, int32(x))
}
func (Leader_LeaderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_leaderlist_ae0131d61a14a58a, []int{0, 0}
}

type Message_MessageType int32

const (
	// messages to sync a list of leaders
	Message_LEADER_SYNC_REQUEST Message_MessageType = 0
	Message_LEADER_SYNC_REPLY   Message_MessageType = 1
	Message_PING_REQUEST        Message_MessageType = 2
	Message_PING_REPLY          Message_MessageType = 3
)

var Message_MessageType_name = map[int32]string{
	0: "LEADER_SYNC_REQUEST",
	1: "LEADER_SYNC_REPLY",
	2: "PING_REQUEST",
	3: "PING_REPLY",
}
var Message_MessageType_value = map[string]int32{
	"LEADER_SYNC_REQUEST": 0,
	"LEADER_SYNC_REPLY":   1,
	"PING_REQUEST":        2,
	"PING_REPLY":          3,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_leaderlist_ae0131d61a14a58a, []int{2, 0}
}

type Leader struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string              `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string              `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Status               Leader_LeaderStatus `protobuf:"varint,4,opt,name=status,enum=leaderlist.Leader_LeaderStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Leader) Reset()         { *m = Leader{} }
func (m *Leader) String() string { return proto.CompactTextString(m) }
func (*Leader) ProtoMessage()    {}
func (*Leader) Descriptor() ([]byte, []int) {
	return fileDescriptor_leaderlist_ae0131d61a14a58a, []int{0}
}
func (m *Leader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leader.Unmarshal(m, b)
}
func (m *Leader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leader.Marshal(b, m, deterministic)
}
func (dst *Leader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leader.Merge(dst, src)
}
func (m *Leader) XXX_Size() int {
	return xxx_messageInfo_Leader.Size(m)
}
func (m *Leader) XXX_DiscardUnknown() {
	xxx_messageInfo_Leader.DiscardUnknown(m)
}

var xxx_messageInfo_Leader proto.InternalMessageInfo

func (m *Leader) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Leader) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Leader) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Leader) GetStatus() Leader_LeaderStatus {
	if m != nil {
		return m.Status
	}
	return Leader_UNKNOWN
}

type LeaderList struct {
	Leader               []*Leader `protobuf:"bytes,1,rep,name=leader" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LeaderList) Reset()         { *m = LeaderList{} }
func (m *LeaderList) String() string { return proto.CompactTextString(m) }
func (*LeaderList) ProtoMessage()    {}
func (*LeaderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_leaderlist_ae0131d61a14a58a, []int{1}
}
func (m *LeaderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderList.Unmarshal(m, b)
}
func (m *LeaderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderList.Marshal(b, m, deterministic)
}
func (dst *LeaderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderList.Merge(dst, src)
}
func (m *LeaderList) XXX_Size() int {
	return xxx_messageInfo_LeaderList.Size(m)
}
func (m *LeaderList) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderList.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderList proto.InternalMessageInfo

func (m *LeaderList) GetLeader() []*Leader {
	if m != nil {
		return m.Leader
	}
	return nil
}

// Services are mapped by request/reply message types
type Message struct {
	MsgType              Message_MessageType `protobuf:"varint,1,opt,name=msgType,enum=leaderlist.Message_MessageType" json:"msgType,omitempty"`
	Sender               *Leader             `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	LeaderList           *LeaderList         `protobuf:"bytes,4,opt,name=leaderList" json:"leaderList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_leaderlist_ae0131d61a14a58a, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() Message_MessageType {
	if m != nil {
		return m.MsgType
	}
	return Message_LEADER_SYNC_REQUEST
}

func (m *Message) GetSender() *Leader {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetLeaderList() *LeaderList {
	if m != nil {
		return m.LeaderList
	}
	return nil
}

func init() {
	proto.RegisterType((*Leader)(nil), "leaderlist.Leader")
	proto.RegisterType((*LeaderList)(nil), "leaderlist.LeaderList")
	proto.RegisterType((*Message)(nil), "leaderlist.Message")
	proto.RegisterEnum("leaderlist.Leader_LeaderStatus", Leader_LeaderStatus_name, Leader_LeaderStatus_value)
	proto.RegisterEnum("leaderlist.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("leaderlist.proto", fileDescriptor_leaderlist_ae0131d61a14a58a) }

var fileDescriptor_leaderlist_ae0131d61a14a58a = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xc7, 0xd9, 0x96, 0x14, 0x99, 0x22, 0x59, 0xc7, 0xa8, 0xbd, 0x49, 0x7a, 0x22, 0x1e, 0x38,
	0x60, 0xe2, 0xc7, 0x91, 0xd0, 0x95, 0x34, 0xd4, 0x2d, 0x6e, 0x8b, 0x84, 0x13, 0xa9, 0xb1, 0x21,
	0x4d, 0xf8, 0x68, 0xd8, 0x7a, 0xf0, 0x11, 0x7c, 0x38, 0xdf, 0xc9, 0x6c, 0x5b, 0xb4, 0x4a, 0x3c,
	0xcd, 0xcc, 0x7f, 0x7e, 0x99, 0xff, 0x74, 0xba, 0x40, 0x57, 0x71, 0xf4, 0x1a, 0xef, 0x56, 0x89,
	0xcc, 0x7a, 0xe9, 0x6e, 0x9b, 0x6d, 0x11, 0x7e, 0x14, 0xfb, 0x93, 0x80, 0xe1, 0xe5, 0x25, 0x22,
	0xd4, 0x37, 0xd1, 0x3a, 0xb6, 0x48, 0x87, 0x74, 0x9b, 0x22, 0xcf, 0xb1, 0x0d, 0x5a, 0x92, 0x5a,
	0x5a, 0xae, 0x68, 0x49, 0xaa, 0x98, 0x74, 0xbb, 0xcb, 0x2c, 0xbd, 0x60, 0x54, 0x8e, 0xb7, 0x60,
	0xc8, 0x2c, 0xca, 0xde, 0xa4, 0x55, 0xef, 0x90, 0x6e, 0xbb, 0x7f, 0xd9, 0xab, 0x38, 0x16, 0xb3,
	0xcb, 0x10, 0xe4, 0x98, 0x28, 0x71, 0x5b, 0x40, 0xab, 0xaa, 0xa3, 0x09, 0x8d, 0x29, 0x1f, 0x73,
	0x7f, 0xc6, 0x69, 0x4d, 0x15, 0x01, 0x13, 0xcf, 0xee, 0x90, 0x51, 0xa2, 0x8a, 0x99, 0x2f, 0xc6,
	0x2e, 0x1f, 0x51, 0x0d, 0x8f, 0xa1, 0x39, 0x1c, 0x70, 0xc7, 0x75, 0x06, 0x21, 0xa3, 0x3a, 0xb6,
	0xe0, 0x88, 0xfb, 0xe1, 0x83, 0x3f, 0xe5, 0x0e, 0xad, 0xdb, 0x77, 0x00, 0xc5, 0x4c, 0x2f, 0x91,
	0x19, 0x5e, 0x81, 0x51, 0xec, 0x62, 0x91, 0x8e, 0xde, 0x35, 0xfb, 0x78, 0xb8, 0x9a, 0x28, 0x09,
	0xfb, 0x43, 0x83, 0xc6, 0x63, 0x2c, 0x65, 0xb4, 0x8c, 0xf1, 0x1e, 0x1a, 0x6b, 0xb9, 0x0c, 0xdf,
	0xd3, 0xe2, 0x1a, 0x7f, 0xbe, 0xa9, 0xa4, 0xf6, 0x51, 0x61, 0x62, 0xcf, 0x2b, 0x4b, 0x19, 0x6f,
	0x94, 0xa5, 0xba, 0xda, 0x3f, 0x96, 0x05, 0x81, 0x37, 0x50, 0xfe, 0x0a, 0xb5, 0x6c, 0x7e, 0x3d,
	0xb3, 0x7f, 0x7e, 0xc8, 0xab, 0xae, 0xa8, 0x90, 0xf6, 0x02, 0xcc, 0x8a, 0x37, 0x5e, 0xc0, 0xa9,
	0xc7, 0x06, 0x0e, 0x13, 0x8b, 0x60, 0xce, 0x87, 0x0b, 0xc1, 0x9e, 0xa6, 0x2c, 0x08, 0x69, 0x0d,
	0xcf, 0xe0, 0xe4, 0x77, 0x63, 0xe2, 0xcd, 0x29, 0x41, 0x0a, 0xad, 0x89, 0xcb, 0x47, 0xdf, 0xa0,
	0x86, 0x6d, 0x80, 0x52, 0x51, 0x84, 0xfe, 0x62, 0xe4, 0x0f, 0xe5, 0xfa, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x69, 0xaf, 0x19, 0x84, 0x3c, 0x02, 0x00, 0x00,
}
