// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat-group.proto

package chatgroup

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_SUBSCRIBE              Message_MessageType = 0
	Message_UNSUBSCRIBE            Message_MessageType = 1
	Message_PUBLISH                Message_MessageType = 2
	Message_DISPLAY_TEXT           Message_MessageType = 3
	Message_DISPLAY_SUBSCRIPTION   Message_MessageType = 4
	Message_DISPLAY_UNSUBSCRIPTION Message_MessageType = 5
)

var Message_MessageType_name = map[int32]string{
	0: "SUBSCRIBE",
	1: "UNSUBSCRIBE",
	2: "PUBLISH",
	3: "DISPLAY_TEXT",
	4: "DISPLAY_SUBSCRIPTION",
	5: "DISPLAY_UNSUBSCRIPTION",
}
var Message_MessageType_value = map[string]int32{
	"SUBSCRIBE":              0,
	"UNSUBSCRIBE":            1,
	"PUBLISH":                2,
	"DISPLAY_TEXT":           3,
	"DISPLAY_SUBSCRIPTION":   4,
	"DISPLAY_UNSUBSCRIPTION": 5,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_3af5ef30bf5e6213, []int{2, 0}
}

type Member struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Leader               bool     `protobuf:"varint,4,opt,name=leader" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_3af5ef30bf5e6213, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Member) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Member) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

type MemberList struct {
	Member               []*Member `protobuf:"bytes,1,rep,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberList) Reset()         { *m = MemberList{} }
func (m *MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()    {}
func (*MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_3af5ef30bf5e6213, []int{1}
}
func (m *MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberList.Unmarshal(m, b)
}
func (m *MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberList.Marshal(b, m, deterministic)
}
func (dst *MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberList.Merge(dst, src)
}
func (m *MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberList.Size(m)
}
func (m *MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberList proto.InternalMessageInfo

func (m *MemberList) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type Message struct {
	MsgType              Message_MessageType `protobuf:"varint,1,opt,name=msgType,enum=chatgroup.Message_MessageType" json:"msgType,omitempty"`
	Sender               *Member             `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	Text                 string              `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_3af5ef30bf5e6213, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() Message_MessageType {
	if m != nil {
		return m.MsgType
	}
	return Message_SUBSCRIBE
}

func (m *Message) GetSender() *Member {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Member)(nil), "chatgroup.Member")
	proto.RegisterType((*MemberList)(nil), "chatgroup.MemberList")
	proto.RegisterType((*Message)(nil), "chatgroup.Message")
	proto.RegisterEnum("chatgroup.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("chat-group.proto", fileDescriptor_chat_group_3af5ef30bf5e6213) }

var fileDescriptor_chat_group_3af5ef30bf5e6213 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xb4, 0xa6, 0x76, 0xa2, 0x75, 0x1d, 0xa4, 0x2c, 0x1e, 0xa4, 0xe4, 0x54, 0x0f,
	0xf6, 0x50, 0x0f, 0x7a, 0x35, 0x5a, 0x30, 0x90, 0xd6, 0x90, 0x3f, 0x50, 0x4f, 0x92, 0xea, 0x12,
	0x03, 0xa6, 0x59, 0x92, 0x08, 0x7a, 0xf5, 0xe2, 0xd7, 0x96, 0xdd, 0x4d, 0xa2, 0x82, 0xa7, 0x9d,
	0x79, 0xf3, 0x9b, 0x99, 0x37, 0x2c, 0xd0, 0xa7, 0x97, 0xa4, 0x3e, 0x4f, 0xcb, 0xe2, 0x4d, 0xcc,
	0x44, 0x59, 0xd4, 0x05, 0x0e, 0xa5, 0xa2, 0x04, 0x7b, 0x0d, 0xe6, 0x92, 0xe7, 0x1b, 0x5e, 0x22,
	0x42, 0x7f, 0x9b, 0xe4, 0x9c, 0x91, 0x09, 0x99, 0x0e, 0x03, 0x15, 0xe3, 0x08, 0x8c, 0x4c, 0x30,
	0x43, 0x29, 0x46, 0x26, 0x24, 0x23, 0x8a, 0xb2, 0x66, 0x3d, 0xcd, 0xc8, 0x18, 0xc7, 0x60, 0xbe,
	0xf2, 0xe4, 0x99, 0x97, 0xac, 0x3f, 0x21, 0xd3, 0xbd, 0xa0, 0xc9, 0xec, 0x4b, 0x00, 0x3d, 0xd9,
	0xcb, 0xaa, 0x1a, 0xcf, 0xc0, 0xcc, 0x55, 0xc6, 0xc8, 0xa4, 0x37, 0xb5, 0xe6, 0x47, 0xb3, 0xce,
	0xc3, 0x4c, 0x63, 0x41, 0x03, 0xd8, 0x5f, 0x06, 0x0c, 0x96, 0xbc, 0xaa, 0x92, 0x94, 0xe3, 0x15,
	0x0c, 0xf2, 0x2a, 0x8d, 0x3e, 0x84, 0xf6, 0x35, 0x9a, 0x9f, 0xfe, 0xe9, 0x53, 0x50, 0xfb, 0x4a,
	0x2a, 0x68, 0x71, 0xb9, 0xb0, 0xe2, 0x5b, 0x69, 0x4b, 0xda, 0xff, 0x7f, 0xa1, 0x06, 0xe4, 0x55,
	0x35, 0x7f, 0xef, 0xae, 0x92, 0xb1, 0xfd, 0x49, 0xc0, 0xfa, 0x35, 0x17, 0x0f, 0x60, 0x18, 0xc6,
	0x4e, 0x78, 0x13, 0xb8, 0xce, 0x82, 0xee, 0xe0, 0x21, 0x58, 0xf1, 0xea, 0x47, 0x20, 0x68, 0xc1,
	0xc0, 0x8f, 0x1d, 0xcf, 0x0d, 0xef, 0xa8, 0x81, 0x14, 0xf6, 0x6f, 0xdd, 0xd0, 0xf7, 0xae, 0x1f,
	0x1e, 0xa3, 0xc5, 0x3a, 0xa2, 0x3d, 0x64, 0x70, 0xdc, 0x2a, 0x4d, 0x97, 0x1f, 0xb9, 0xf7, 0x2b,
	0xda, 0xc7, 0x13, 0x18, 0xb7, 0x95, 0x6e, 0xa2, 0xae, 0xed, 0x6e, 0x4c, 0xf5, 0x5d, 0x17, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x42, 0x1f, 0xb3, 0xc2, 0x01, 0x00, 0x00,
}
